# See dos how to configure the bundle: https://symfony.com/doc/current/bundles/LiipImagineBundle/basic-usage.html
liip_imagine:
    # valid drivers options include "gd" or "gmagick" or "imagick"
    driver: "gd"
    filter_sets:

        # Paramétrage de l'affichage de l'image de profil dans la "mon profil"
        profil:
            quality: 100                    # Qualité 100%
            filters:
                scale:                      # Si l'image est plus grande, elle sera redimensionnée sans découpe et en gardant le même ratio largeur/hauteur
                    dim: [ 200, 200 ]       # 200px maximum en hauteur et en largeur

        # Paramétrage de l'affichage de l'image de profil dans les commentaires
        comment:
            quality: 100                    # Qualité 100%
            filters:
                scale:                      # Si l'image est plus grande, elle sera redimensionnée sans découpe et en gardant le même ratio largeur/hauteur
                    dim: [80, 80]           # 80px maximum en hauteur et en largeur